// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: itd_ipd_nmea_msgs.proto

#ifndef PROTOBUF_itd_5fipd_5fnmea_5fmsgs_2eproto__INCLUDED
#define PROTOBUF_itd_5fipd_5fnmea_5fmsgs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "itd_ipd_std_msgs.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_itd_5fipd_5fnmea_5fmsgs_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsGps84Impl();
void InitDefaultsGps84();
inline void InitDefaults() {
  InitDefaultsGps84();
}
}  // namespace protobuf_itd_5fipd_5fnmea_5fmsgs_2eproto
namespace itd {
namespace communication {
namespace protobuf {
class Gps84;
class Gps84DefaultTypeInternal;
extern Gps84DefaultTypeInternal _Gps84_default_instance_;
}  // namespace protobuf
}  // namespace communication
}  // namespace itd
namespace itd {
namespace communication {
namespace protobuf {

// ===================================================================

class Gps84 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:itd.communication.protobuf.Gps84) */ {
 public:
  Gps84();
  virtual ~Gps84();

  Gps84(const Gps84& from);

  inline Gps84& operator=(const Gps84& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Gps84(Gps84&& from) noexcept
    : Gps84() {
    *this = ::std::move(from);
  }

  inline Gps84& operator=(Gps84&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Gps84& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Gps84* internal_default_instance() {
    return reinterpret_cast<const Gps84*>(
               &_Gps84_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void UnsafeArenaSwap(Gps84* other);
  void Swap(Gps84* other);
  friend void swap(Gps84& a, Gps84& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Gps84* New() const PROTOBUF_FINAL { return New(NULL); }

  Gps84* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Gps84& from);
  void MergeFrom(const Gps84& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Gps84* other);
  protected:
  explicit Gps84(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message_id = 2;
  void clear_message_id();
  static const int kMessageIdFieldNumber = 2;
  const ::std::string& message_id() const;
  void set_message_id(const ::std::string& value);
  #if LANG_CXX11
  void set_message_id(::std::string&& value);
  #endif
  void set_message_id(const char* value);
  void set_message_id(const char* value, size_t size);
  ::std::string* mutable_message_id();
  ::std::string* release_message_id();
  void set_allocated_message_id(::std::string* message_id);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_message_id();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message_id(
      ::std::string* message_id);

  // .itd.communication.protobuf.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  void _slow_mutable_header();
  public:
  const ::itd::communication::protobuf::Header& header() const;
  ::itd::communication::protobuf::Header* release_header();
  ::itd::communication::protobuf::Header* mutable_header();
  void set_allocated_header(::itd::communication::protobuf::Header* header);
  void unsafe_arena_set_allocated_header(
      ::itd::communication::protobuf::Header* header);
  ::itd::communication::protobuf::Header* unsafe_arena_release_header();

  // double latitude = 3;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 3;
  double latitude() const;
  void set_latitude(double value);

  // double longitude = 4;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 4;
  double longitude() const;
  void set_longitude(double value);

  // double altitude = 5;
  void clear_altitude();
  static const int kAltitudeFieldNumber = 5;
  double altitude() const;
  void set_altitude(double value);

  // double utc_sec = 7;
  void clear_utc_sec();
  static const int kUtcSecFieldNumber = 7;
  double utc_sec() const;
  void set_utc_sec(double value);

  // float speed = 6;
  void clear_speed();
  static const int kSpeedFieldNumber = 6;
  float speed() const;
  void set_speed(float value);

  // @@protoc_insertion_point(class_scope:itd.communication.protobuf.Gps84)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::ArenaStringPtr message_id_;
  ::itd::communication::protobuf::Header* header_;
  double latitude_;
  double longitude_;
  double altitude_;
  double utc_sec_;
  float speed_;
  mutable int _cached_size_;
  friend struct ::protobuf_itd_5fipd_5fnmea_5fmsgs_2eproto::TableStruct;
  friend void ::protobuf_itd_5fipd_5fnmea_5fmsgs_2eproto::InitDefaultsGps84Impl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Gps84

// .itd.communication.protobuf.Header header = 1;
inline bool Gps84::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::itd::communication::protobuf::Header& Gps84::header() const {
  const ::itd::communication::protobuf::Header* p = header_;
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Gps84.header)
  return p != NULL ? *p : *reinterpret_cast<const ::itd::communication::protobuf::Header*>(
      &::itd::communication::protobuf::_Header_default_instance_);
}
inline ::itd::communication::protobuf::Header* Gps84::release_header() {
  // @@protoc_insertion_point(field_release:itd.communication.protobuf.Gps84.header)
  
  ::itd::communication::protobuf::Header* temp = header_;
  if (GetArenaNoVirtual() != NULL) {
    temp = ::google::protobuf::internal::DuplicateIfNonNull(temp, NULL);
  }
  header_ = NULL;
  return temp;
}
inline ::itd::communication::protobuf::Header* Gps84::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_unsafe_arena_release:itd.communication.protobuf.Gps84.header)
  
  ::itd::communication::protobuf::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::itd::communication::protobuf::Header* Gps84::mutable_header() {
  
  if (header_ == NULL) {
    _slow_mutable_header();
  }
  // @@protoc_insertion_point(field_mutable:itd.communication.protobuf.Gps84.header)
  return header_;
}
inline void Gps84::set_allocated_header(::itd::communication::protobuf::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast< ::google::protobuf::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:itd.communication.protobuf.Gps84.header)
}

// string message_id = 2;
inline void Gps84::clear_message_id() {
  message_id_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& Gps84::message_id() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Gps84.message_id)
  return message_id_.Get();
}
inline void Gps84::set_message_id(const ::std::string& value) {
  
  message_id_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.Gps84.message_id)
}
#if LANG_CXX11
inline void Gps84::set_message_id(::std::string&& value) {
  
  message_id_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:itd.communication.protobuf.Gps84.message_id)
}
#endif
inline void Gps84::set_message_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_id_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:itd.communication.protobuf.Gps84.message_id)
}
inline void Gps84::set_message_id(const char* value,
    size_t size) {
  
  message_id_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:itd.communication.protobuf.Gps84.message_id)
}
inline ::std::string* Gps84::mutable_message_id() {
  
  // @@protoc_insertion_point(field_mutable:itd.communication.protobuf.Gps84.message_id)
  return message_id_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Gps84::release_message_id() {
  // @@protoc_insertion_point(field_release:itd.communication.protobuf.Gps84.message_id)
  
  return message_id_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void Gps84::set_allocated_message_id(::std::string* message_id) {
  if (message_id != NULL) {
    
  } else {
    
  }
  message_id_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message_id,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:itd.communication.protobuf.Gps84.message_id)
}
inline ::std::string* Gps84::unsafe_arena_release_message_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:itd.communication.protobuf.Gps84.message_id)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return message_id_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void Gps84::unsafe_arena_set_allocated_message_id(
    ::std::string* message_id) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (message_id != NULL) {
    
  } else {
    
  }
  message_id_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      message_id, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:itd.communication.protobuf.Gps84.message_id)
}

// double latitude = 3;
inline void Gps84::clear_latitude() {
  latitude_ = 0;
}
inline double Gps84::latitude() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Gps84.latitude)
  return latitude_;
}
inline void Gps84::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.Gps84.latitude)
}

// double longitude = 4;
inline void Gps84::clear_longitude() {
  longitude_ = 0;
}
inline double Gps84::longitude() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Gps84.longitude)
  return longitude_;
}
inline void Gps84::set_longitude(double value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.Gps84.longitude)
}

// double altitude = 5;
inline void Gps84::clear_altitude() {
  altitude_ = 0;
}
inline double Gps84::altitude() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Gps84.altitude)
  return altitude_;
}
inline void Gps84::set_altitude(double value) {
  
  altitude_ = value;
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.Gps84.altitude)
}

// float speed = 6;
inline void Gps84::clear_speed() {
  speed_ = 0;
}
inline float Gps84::speed() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Gps84.speed)
  return speed_;
}
inline void Gps84::set_speed(float value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.Gps84.speed)
}

// double utc_sec = 7;
inline void Gps84::clear_utc_sec() {
  utc_sec_ = 0;
}
inline double Gps84::utc_sec() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Gps84.utc_sec)
  return utc_sec_;
}
inline void Gps84::set_utc_sec(double value) {
  
  utc_sec_ = value;
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.Gps84.utc_sec)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace communication
}  // namespace itd

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_itd_5fipd_5fnmea_5fmsgs_2eproto__INCLUDED
