// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef PROTOBUF_msg_2eproto__INCLUDED
#define PROTOBUF_msg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_msg_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsHeaderImpl();
void InitDefaultsHeader();
void InitDefaultsPointCloudImpl();
void InitDefaultsPointCloud();
void InitDefaultsMessageImpl();
void InitDefaultsMessage();
inline void InitDefaults() {
  InitDefaultsHeader();
  InitDefaultsPointCloud();
  InitDefaultsMessage();
}
}  // namespace protobuf_msg_2eproto
namespace itd {
namespace communication {
namespace protobuf {
class Header;
class HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class PointCloud;
class PointCloudDefaultTypeInternal;
extern PointCloudDefaultTypeInternal _PointCloud_default_instance_;
}  // namespace protobuf
}  // namespace communication
}  // namespace itd
namespace itd {
namespace communication {
namespace protobuf {

enum Message_MessageType {
  Message_MessageType_PointCloud = 0,
  Message_MessageType_Message_MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Message_MessageType_Message_MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Message_MessageType_IsValid(int value);
const Message_MessageType Message_MessageType_MessageType_MIN = Message_MessageType_PointCloud;
const Message_MessageType Message_MessageType_MessageType_MAX = Message_MessageType_PointCloud;
const int Message_MessageType_MessageType_ARRAYSIZE = Message_MessageType_MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Message_MessageType_descriptor();
inline const ::std::string& Message_MessageType_Name(Message_MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Message_MessageType_descriptor(), value);
}
inline bool Message_MessageType_Parse(
    const ::std::string& name, Message_MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Message_MessageType>(
    Message_MessageType_descriptor(), name, value);
}
// ===================================================================

class Header : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:itd.communication.protobuf.Header) */ {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(Header&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void UnsafeArenaSwap(Header* other);
  void Swap(Header* other);
  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Header* New() const PROTOBUF_FINAL { return New(NULL); }

  Header* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Header* other);
  protected:
  explicit Header(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string frame_id = 3;
  void clear_frame_id();
  static const int kFrameIdFieldNumber = 3;
  const ::std::string& frame_id() const;
  void set_frame_id(const ::std::string& value);
  #if LANG_CXX11
  void set_frame_id(::std::string&& value);
  #endif
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  ::std::string* mutable_frame_id();
  ::std::string* release_frame_id();
  void set_allocated_frame_id(::std::string* frame_id);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_frame_id();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_frame_id(
      ::std::string* frame_id);

  // uint32 seq = 1;
  void clear_seq();
  static const int kSeqFieldNumber = 1;
  ::google::protobuf::uint32 seq() const;
  void set_seq(::google::protobuf::uint32 value);

  // int32 stamp = 2;
  void clear_stamp();
  static const int kStampFieldNumber = 2;
  ::google::protobuf::int32 stamp() const;
  void set_stamp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:itd.communication.protobuf.Header)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::ArenaStringPtr frame_id_;
  ::google::protobuf::uint32 seq_;
  ::google::protobuf::int32 stamp_;
  mutable int _cached_size_;
  friend struct ::protobuf_msg_2eproto::TableStruct;
  friend void ::protobuf_msg_2eproto::InitDefaultsHeaderImpl();
};
// -------------------------------------------------------------------

class PointCloud : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:itd.communication.protobuf.PointCloud) */ {
 public:
  PointCloud();
  virtual ~PointCloud();

  PointCloud(const PointCloud& from);

  inline PointCloud& operator=(const PointCloud& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PointCloud(PointCloud&& from) noexcept
    : PointCloud() {
    *this = ::std::move(from);
  }

  inline PointCloud& operator=(PointCloud&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const PointCloud& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PointCloud* internal_default_instance() {
    return reinterpret_cast<const PointCloud*>(
               &_PointCloud_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void UnsafeArenaSwap(PointCloud* other);
  void Swap(PointCloud* other);
  friend void swap(PointCloud& a, PointCloud& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PointCloud* New() const PROTOBUF_FINAL { return New(NULL); }

  PointCloud* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PointCloud& from);
  void MergeFrom(const PointCloud& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PointCloud* other);
  protected:
  explicit PointCloud(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float x = 4;
  int x_size() const;
  void clear_x();
  static const int kXFieldNumber = 4;
  float x(int index) const;
  void set_x(int index, float value);
  void add_x(float value);
  const ::google::protobuf::RepeatedField< float >&
      x() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_x();

  // repeated float y = 5;
  int y_size() const;
  void clear_y();
  static const int kYFieldNumber = 5;
  float y(int index) const;
  void set_y(int index, float value);
  void add_y(float value);
  const ::google::protobuf::RepeatedField< float >&
      y() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_y();

  // repeated float z = 6;
  int z_size() const;
  void clear_z();
  static const int kZFieldNumber = 6;
  float z(int index) const;
  void set_z(int index, float value);
  void add_z(float value);
  const ::google::protobuf::RepeatedField< float >&
      z() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_z();

  // repeated float intensity = 7;
  int intensity_size() const;
  void clear_intensity();
  static const int kIntensityFieldNumber = 7;
  float intensity(int index) const;
  void set_intensity(int index, float value);
  void add_intensity(float value);
  const ::google::protobuf::RepeatedField< float >&
      intensity() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_intensity();

  // repeated float ring = 8;
  int ring_size() const;
  void clear_ring();
  static const int kRingFieldNumber = 8;
  float ring(int index) const;
  void set_ring(int index, float value);
  void add_ring(float value);
  const ::google::protobuf::RepeatedField< float >&
      ring() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_ring();

  // repeated float azimuth = 9;
  int azimuth_size() const;
  void clear_azimuth();
  static const int kAzimuthFieldNumber = 9;
  float azimuth(int index) const;
  void set_azimuth(int index, float value);
  void add_azimuth(float value);
  const ::google::protobuf::RepeatedField< float >&
      azimuth() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_azimuth();

  // repeated float hor = 10;
  int hor_size() const;
  void clear_hor();
  static const int kHorFieldNumber = 10;
  float hor(int index) const;
  void set_hor(int index, float value);
  void add_hor(float value);
  const ::google::protobuf::RepeatedField< float >&
      hor() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_hor();

  // repeated float time_offset = 11;
  int time_offset_size() const;
  void clear_time_offset();
  static const int kTimeOffsetFieldNumber = 11;
  float time_offset(int index) const;
  void set_time_offset(int index, float value);
  void add_time_offset(float value);
  const ::google::protobuf::RepeatedField< float >&
      time_offset() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_time_offset();

  // repeated float distance = 12;
  int distance_size() const;
  void clear_distance();
  static const int kDistanceFieldNumber = 12;
  float distance(int index) const;
  void set_distance(int index, float value);
  void add_distance(float value);
  const ::google::protobuf::RepeatedField< float >&
      distance() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_distance();

  // .itd.communication.protobuf.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  void _slow_mutable_header();
  public:
  const ::itd::communication::protobuf::Header& header() const;
  ::itd::communication::protobuf::Header* release_header();
  ::itd::communication::protobuf::Header* mutable_header();
  void set_allocated_header(::itd::communication::protobuf::Header* header);
  void unsafe_arena_set_allocated_header(
      ::itd::communication::protobuf::Header* header);
  ::itd::communication::protobuf::Header* unsafe_arena_release_header();

  // uint32 height = 2;
  void clear_height();
  static const int kHeightFieldNumber = 2;
  ::google::protobuf::uint32 height() const;
  void set_height(::google::protobuf::uint32 value);

  // uint32 width = 3;
  void clear_width();
  static const int kWidthFieldNumber = 3;
  ::google::protobuf::uint32 width() const;
  void set_width(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:itd.communication.protobuf.PointCloud)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::RepeatedField< float > x_;
  mutable int _x_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > y_;
  mutable int _y_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > z_;
  mutable int _z_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > intensity_;
  mutable int _intensity_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > ring_;
  mutable int _ring_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > azimuth_;
  mutable int _azimuth_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > hor_;
  mutable int _hor_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > time_offset_;
  mutable int _time_offset_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > distance_;
  mutable int _distance_cached_byte_size_;
  ::itd::communication::protobuf::Header* header_;
  ::google::protobuf::uint32 height_;
  ::google::protobuf::uint32 width_;
  mutable int _cached_size_;
  friend struct ::protobuf_msg_2eproto::TableStruct;
  friend void ::protobuf_msg_2eproto::InitDefaultsPointCloudImpl();
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:itd.communication.protobuf.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  enum MsgCase {
    kCloud = 2,
    MSG_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void UnsafeArenaSwap(Message* other);
  void Swap(Message* other);
  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const PROTOBUF_FINAL { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message* other);
  protected:
  explicit Message(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Message_MessageType MessageType;
  static const MessageType PointCloud =
    Message_MessageType_PointCloud;
  static inline bool MessageType_IsValid(int value) {
    return Message_MessageType_IsValid(value);
  }
  static const MessageType MessageType_MIN =
    Message_MessageType_MessageType_MIN;
  static const MessageType MessageType_MAX =
    Message_MessageType_MessageType_MAX;
  static const int MessageType_ARRAYSIZE =
    Message_MessageType_MessageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MessageType_descriptor() {
    return Message_MessageType_descriptor();
  }
  static inline const ::std::string& MessageType_Name(MessageType value) {
    return Message_MessageType_Name(value);
  }
  static inline bool MessageType_Parse(const ::std::string& name,
      MessageType* value) {
    return Message_MessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .itd.communication.protobuf.Message.MessageType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::itd::communication::protobuf::Message_MessageType type() const;
  void set_type(::itd::communication::protobuf::Message_MessageType value);

  // .itd.communication.protobuf.PointCloud cloud = 2;
  bool has_cloud() const;
  void clear_cloud();
  static const int kCloudFieldNumber = 2;
  private:
  void _slow_mutable_cloud();
  public:
  const ::itd::communication::protobuf::PointCloud& cloud() const;
  ::itd::communication::protobuf::PointCloud* release_cloud();
  ::itd::communication::protobuf::PointCloud* mutable_cloud();
  void set_allocated_cloud(::itd::communication::protobuf::PointCloud* cloud);
  void unsafe_arena_set_allocated_cloud(
      ::itd::communication::protobuf::PointCloud* cloud);
  ::itd::communication::protobuf::PointCloud* unsafe_arena_release_cloud();

  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:itd.communication.protobuf.Message)
 private:
  void set_has_cloud();

  inline bool has_msg() const;
  void clear_msg();
  inline void clear_has_msg();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int type_;
  union MsgUnion {
    MsgUnion() {}
    ::itd::communication::protobuf::PointCloud* cloud_;
  } msg_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_msg_2eproto::TableStruct;
  friend void ::protobuf_msg_2eproto::InitDefaultsMessageImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Header

// uint32 seq = 1;
inline void Header::clear_seq() {
  seq_ = 0u;
}
inline ::google::protobuf::uint32 Header::seq() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Header.seq)
  return seq_;
}
inline void Header::set_seq(::google::protobuf::uint32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.Header.seq)
}

// int32 stamp = 2;
inline void Header::clear_stamp() {
  stamp_ = 0;
}
inline ::google::protobuf::int32 Header::stamp() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Header.stamp)
  return stamp_;
}
inline void Header::set_stamp(::google::protobuf::int32 value) {
  
  stamp_ = value;
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.Header.stamp)
}

// string frame_id = 3;
inline void Header::clear_frame_id() {
  frame_id_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& Header::frame_id() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Header.frame_id)
  return frame_id_.Get();
}
inline void Header::set_frame_id(const ::std::string& value) {
  
  frame_id_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.Header.frame_id)
}
#if LANG_CXX11
inline void Header::set_frame_id(::std::string&& value) {
  
  frame_id_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:itd.communication.protobuf.Header.frame_id)
}
#endif
inline void Header::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  frame_id_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:itd.communication.protobuf.Header.frame_id)
}
inline void Header::set_frame_id(const char* value,
    size_t size) {
  
  frame_id_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:itd.communication.protobuf.Header.frame_id)
}
inline ::std::string* Header::mutable_frame_id() {
  
  // @@protoc_insertion_point(field_mutable:itd.communication.protobuf.Header.frame_id)
  return frame_id_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Header::release_frame_id() {
  // @@protoc_insertion_point(field_release:itd.communication.protobuf.Header.frame_id)
  
  return frame_id_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void Header::set_allocated_frame_id(::std::string* frame_id) {
  if (frame_id != NULL) {
    
  } else {
    
  }
  frame_id_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frame_id,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:itd.communication.protobuf.Header.frame_id)
}
inline ::std::string* Header::unsafe_arena_release_frame_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:itd.communication.protobuf.Header.frame_id)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return frame_id_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void Header::unsafe_arena_set_allocated_frame_id(
    ::std::string* frame_id) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (frame_id != NULL) {
    
  } else {
    
  }
  frame_id_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      frame_id, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:itd.communication.protobuf.Header.frame_id)
}

// -------------------------------------------------------------------

// PointCloud

// .itd.communication.protobuf.Header header = 1;
inline bool PointCloud::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline void PointCloud::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
}
inline const ::itd::communication::protobuf::Header& PointCloud::header() const {
  const ::itd::communication::protobuf::Header* p = header_;
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.header)
  return p != NULL ? *p : *reinterpret_cast<const ::itd::communication::protobuf::Header*>(
      &::itd::communication::protobuf::_Header_default_instance_);
}
inline ::itd::communication::protobuf::Header* PointCloud::release_header() {
  // @@protoc_insertion_point(field_release:itd.communication.protobuf.PointCloud.header)
  
  ::itd::communication::protobuf::Header* temp = header_;
  if (GetArenaNoVirtual() != NULL) {
    temp = ::google::protobuf::internal::DuplicateIfNonNull(temp, NULL);
  }
  header_ = NULL;
  return temp;
}
inline ::itd::communication::protobuf::Header* PointCloud::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_unsafe_arena_release:itd.communication.protobuf.PointCloud.header)
  
  ::itd::communication::protobuf::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::itd::communication::protobuf::Header* PointCloud::mutable_header() {
  
  if (header_ == NULL) {
    _slow_mutable_header();
  }
  // @@protoc_insertion_point(field_mutable:itd.communication.protobuf.PointCloud.header)
  return header_;
}
inline void PointCloud::set_allocated_header(::itd::communication::protobuf::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete header_;
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena =
      ::google::protobuf::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:itd.communication.protobuf.PointCloud.header)
}

// uint32 height = 2;
inline void PointCloud::clear_height() {
  height_ = 0u;
}
inline ::google::protobuf::uint32 PointCloud::height() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.height)
  return height_;
}
inline void PointCloud::set_height(::google::protobuf::uint32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.height)
}

// uint32 width = 3;
inline void PointCloud::clear_width() {
  width_ = 0u;
}
inline ::google::protobuf::uint32 PointCloud::width() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.width)
  return width_;
}
inline void PointCloud::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.width)
}

// repeated float x = 4;
inline int PointCloud::x_size() const {
  return x_.size();
}
inline void PointCloud::clear_x() {
  x_.Clear();
}
inline float PointCloud::x(int index) const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.x)
  return x_.Get(index);
}
inline void PointCloud::set_x(int index, float value) {
  x_.Set(index, value);
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.x)
}
inline void PointCloud::add_x(float value) {
  x_.Add(value);
  // @@protoc_insertion_point(field_add:itd.communication.protobuf.PointCloud.x)
}
inline const ::google::protobuf::RepeatedField< float >&
PointCloud::x() const {
  // @@protoc_insertion_point(field_list:itd.communication.protobuf.PointCloud.x)
  return x_;
}
inline ::google::protobuf::RepeatedField< float >*
PointCloud::mutable_x() {
  // @@protoc_insertion_point(field_mutable_list:itd.communication.protobuf.PointCloud.x)
  return &x_;
}

// repeated float y = 5;
inline int PointCloud::y_size() const {
  return y_.size();
}
inline void PointCloud::clear_y() {
  y_.Clear();
}
inline float PointCloud::y(int index) const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.y)
  return y_.Get(index);
}
inline void PointCloud::set_y(int index, float value) {
  y_.Set(index, value);
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.y)
}
inline void PointCloud::add_y(float value) {
  y_.Add(value);
  // @@protoc_insertion_point(field_add:itd.communication.protobuf.PointCloud.y)
}
inline const ::google::protobuf::RepeatedField< float >&
PointCloud::y() const {
  // @@protoc_insertion_point(field_list:itd.communication.protobuf.PointCloud.y)
  return y_;
}
inline ::google::protobuf::RepeatedField< float >*
PointCloud::mutable_y() {
  // @@protoc_insertion_point(field_mutable_list:itd.communication.protobuf.PointCloud.y)
  return &y_;
}

// repeated float z = 6;
inline int PointCloud::z_size() const {
  return z_.size();
}
inline void PointCloud::clear_z() {
  z_.Clear();
}
inline float PointCloud::z(int index) const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.z)
  return z_.Get(index);
}
inline void PointCloud::set_z(int index, float value) {
  z_.Set(index, value);
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.z)
}
inline void PointCloud::add_z(float value) {
  z_.Add(value);
  // @@protoc_insertion_point(field_add:itd.communication.protobuf.PointCloud.z)
}
inline const ::google::protobuf::RepeatedField< float >&
PointCloud::z() const {
  // @@protoc_insertion_point(field_list:itd.communication.protobuf.PointCloud.z)
  return z_;
}
inline ::google::protobuf::RepeatedField< float >*
PointCloud::mutable_z() {
  // @@protoc_insertion_point(field_mutable_list:itd.communication.protobuf.PointCloud.z)
  return &z_;
}

// repeated float intensity = 7;
inline int PointCloud::intensity_size() const {
  return intensity_.size();
}
inline void PointCloud::clear_intensity() {
  intensity_.Clear();
}
inline float PointCloud::intensity(int index) const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.intensity)
  return intensity_.Get(index);
}
inline void PointCloud::set_intensity(int index, float value) {
  intensity_.Set(index, value);
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.intensity)
}
inline void PointCloud::add_intensity(float value) {
  intensity_.Add(value);
  // @@protoc_insertion_point(field_add:itd.communication.protobuf.PointCloud.intensity)
}
inline const ::google::protobuf::RepeatedField< float >&
PointCloud::intensity() const {
  // @@protoc_insertion_point(field_list:itd.communication.protobuf.PointCloud.intensity)
  return intensity_;
}
inline ::google::protobuf::RepeatedField< float >*
PointCloud::mutable_intensity() {
  // @@protoc_insertion_point(field_mutable_list:itd.communication.protobuf.PointCloud.intensity)
  return &intensity_;
}

// repeated float ring = 8;
inline int PointCloud::ring_size() const {
  return ring_.size();
}
inline void PointCloud::clear_ring() {
  ring_.Clear();
}
inline float PointCloud::ring(int index) const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.ring)
  return ring_.Get(index);
}
inline void PointCloud::set_ring(int index, float value) {
  ring_.Set(index, value);
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.ring)
}
inline void PointCloud::add_ring(float value) {
  ring_.Add(value);
  // @@protoc_insertion_point(field_add:itd.communication.protobuf.PointCloud.ring)
}
inline const ::google::protobuf::RepeatedField< float >&
PointCloud::ring() const {
  // @@protoc_insertion_point(field_list:itd.communication.protobuf.PointCloud.ring)
  return ring_;
}
inline ::google::protobuf::RepeatedField< float >*
PointCloud::mutable_ring() {
  // @@protoc_insertion_point(field_mutable_list:itd.communication.protobuf.PointCloud.ring)
  return &ring_;
}

// repeated float azimuth = 9;
inline int PointCloud::azimuth_size() const {
  return azimuth_.size();
}
inline void PointCloud::clear_azimuth() {
  azimuth_.Clear();
}
inline float PointCloud::azimuth(int index) const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.azimuth)
  return azimuth_.Get(index);
}
inline void PointCloud::set_azimuth(int index, float value) {
  azimuth_.Set(index, value);
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.azimuth)
}
inline void PointCloud::add_azimuth(float value) {
  azimuth_.Add(value);
  // @@protoc_insertion_point(field_add:itd.communication.protobuf.PointCloud.azimuth)
}
inline const ::google::protobuf::RepeatedField< float >&
PointCloud::azimuth() const {
  // @@protoc_insertion_point(field_list:itd.communication.protobuf.PointCloud.azimuth)
  return azimuth_;
}
inline ::google::protobuf::RepeatedField< float >*
PointCloud::mutable_azimuth() {
  // @@protoc_insertion_point(field_mutable_list:itd.communication.protobuf.PointCloud.azimuth)
  return &azimuth_;
}

// repeated float hor = 10;
inline int PointCloud::hor_size() const {
  return hor_.size();
}
inline void PointCloud::clear_hor() {
  hor_.Clear();
}
inline float PointCloud::hor(int index) const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.hor)
  return hor_.Get(index);
}
inline void PointCloud::set_hor(int index, float value) {
  hor_.Set(index, value);
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.hor)
}
inline void PointCloud::add_hor(float value) {
  hor_.Add(value);
  // @@protoc_insertion_point(field_add:itd.communication.protobuf.PointCloud.hor)
}
inline const ::google::protobuf::RepeatedField< float >&
PointCloud::hor() const {
  // @@protoc_insertion_point(field_list:itd.communication.protobuf.PointCloud.hor)
  return hor_;
}
inline ::google::protobuf::RepeatedField< float >*
PointCloud::mutable_hor() {
  // @@protoc_insertion_point(field_mutable_list:itd.communication.protobuf.PointCloud.hor)
  return &hor_;
}

// repeated float time_offset = 11;
inline int PointCloud::time_offset_size() const {
  return time_offset_.size();
}
inline void PointCloud::clear_time_offset() {
  time_offset_.Clear();
}
inline float PointCloud::time_offset(int index) const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.time_offset)
  return time_offset_.Get(index);
}
inline void PointCloud::set_time_offset(int index, float value) {
  time_offset_.Set(index, value);
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.time_offset)
}
inline void PointCloud::add_time_offset(float value) {
  time_offset_.Add(value);
  // @@protoc_insertion_point(field_add:itd.communication.protobuf.PointCloud.time_offset)
}
inline const ::google::protobuf::RepeatedField< float >&
PointCloud::time_offset() const {
  // @@protoc_insertion_point(field_list:itd.communication.protobuf.PointCloud.time_offset)
  return time_offset_;
}
inline ::google::protobuf::RepeatedField< float >*
PointCloud::mutable_time_offset() {
  // @@protoc_insertion_point(field_mutable_list:itd.communication.protobuf.PointCloud.time_offset)
  return &time_offset_;
}

// repeated float distance = 12;
inline int PointCloud::distance_size() const {
  return distance_.size();
}
inline void PointCloud::clear_distance() {
  distance_.Clear();
}
inline float PointCloud::distance(int index) const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.PointCloud.distance)
  return distance_.Get(index);
}
inline void PointCloud::set_distance(int index, float value) {
  distance_.Set(index, value);
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.PointCloud.distance)
}
inline void PointCloud::add_distance(float value) {
  distance_.Add(value);
  // @@protoc_insertion_point(field_add:itd.communication.protobuf.PointCloud.distance)
}
inline const ::google::protobuf::RepeatedField< float >&
PointCloud::distance() const {
  // @@protoc_insertion_point(field_list:itd.communication.protobuf.PointCloud.distance)
  return distance_;
}
inline ::google::protobuf::RepeatedField< float >*
PointCloud::mutable_distance() {
  // @@protoc_insertion_point(field_mutable_list:itd.communication.protobuf.PointCloud.distance)
  return &distance_;
}

// -------------------------------------------------------------------

// Message

// .itd.communication.protobuf.Message.MessageType type = 1;
inline void Message::clear_type() {
  type_ = 0;
}
inline ::itd::communication::protobuf::Message_MessageType Message::type() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Message.type)
  return static_cast< ::itd::communication::protobuf::Message_MessageType >(type_);
}
inline void Message::set_type(::itd::communication::protobuf::Message_MessageType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:itd.communication.protobuf.Message.type)
}

// .itd.communication.protobuf.PointCloud cloud = 2;
inline bool Message::has_cloud() const {
  return msg_case() == kCloud;
}
inline void Message::set_has_cloud() {
  _oneof_case_[0] = kCloud;
}
inline void Message::clear_cloud() {
  if (has_cloud()) {
    if (GetArenaNoVirtual() == NULL) {
      delete msg_.cloud_;
    }
    clear_has_msg();
  }
}
inline ::itd::communication::protobuf::PointCloud* Message::release_cloud() {
  // @@protoc_insertion_point(field_release:itd.communication.protobuf.Message.cloud)
  if (has_cloud()) {
    clear_has_msg();
      ::itd::communication::protobuf::PointCloud* temp = msg_.cloud_;
    if (GetArenaNoVirtual() != NULL) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp, NULL);
    }
    msg_.cloud_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::itd::communication::protobuf::PointCloud& Message::cloud() const {
  // @@protoc_insertion_point(field_get:itd.communication.protobuf.Message.cloud)
  return has_cloud()
      ? *msg_.cloud_
      : *reinterpret_cast< ::itd::communication::protobuf::PointCloud*>(&::itd::communication::protobuf::_PointCloud_default_instance_);
}
inline ::itd::communication::protobuf::PointCloud* Message::unsafe_arena_release_cloud() {
  // @@protoc_insertion_point(field_unsafe_arena_release:itd.communication.protobuf.Message.cloud)
  if (has_cloud()) {
    clear_has_msg();
    ::itd::communication::protobuf::PointCloud* temp = msg_.cloud_;
    msg_.cloud_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Message::unsafe_arena_set_allocated_cloud(::itd::communication::protobuf::PointCloud* cloud) {
  clear_msg();
  if (cloud) {
    set_has_cloud();
    msg_.cloud_ = cloud;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:itd.communication.protobuf.Message.cloud)
}
inline ::itd::communication::protobuf::PointCloud* Message::mutable_cloud() {
  if (!has_cloud()) {
    clear_msg();
    set_has_cloud();
    msg_.cloud_ = 
      ::google::protobuf::Arena::CreateMessage< ::itd::communication::protobuf::PointCloud >(
      GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:itd.communication.protobuf.Message.cloud)
  return msg_.cloud_;
}

inline bool Message::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void Message::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
inline Message::MsgCase Message::msg_case() const {
  return Message::MsgCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace communication
}  // namespace itd

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::itd::communication::protobuf::Message_MessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::itd::communication::protobuf::Message_MessageType>() {
  return ::itd::communication::protobuf::Message_MessageType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_2eproto__INCLUDED
